data_ingestion:
 bucket_name: "tap30-demand"
 object_name: "tap30_demand_prediction.txt"
 storage_path: "s3.ir-thr-at1.arvanstorage.ir"
 train_ratio: 0.9
 artifact_dir: "artifacts"

data_processing:
 shift: 18

model_training:
  # Common parameters
  seed: 42
  n_jobs: -1
  
  # RandomForest specific parameters
  n_estimators: 300
  max_samples: 0.6
  oob_score: True
  
  # XGBoost specific parameters
  xgb_n_estimators: 1000
  learning_rate: 0.05
  max_depth: 8
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.01
  reg_lambda: 1.0
  
  # Model selection (options: "random_forest", "xgboost")
  model_type: "xgboost"

web:
  port: 8080
  host: "0.0.0.0"
  model_output_dir: "artifacts/models"
  model_name: "xgboost.joblib"
